require 'dotenv/load'

TOKEN = ENV['TOKEN']
MASTER_ID = ENV['MASTER_ID'].to_i
CALENDAR_ID = ENV['CALENDAR_ID']
MONGO_URL = ENV['MONGO_URL']
YOO_KASSA_TOKEN = ENV['YOO_KASSA_TOKEN']
ALEX_SPOON = ENV['ALEX_SPOON'].to_i
