require 'dotenv/load'

TOKEN = ENV['TOKEN']
MASTER_ID = ENV['MASTER_ID'].to_i
CALENDAR_ID = ENV['CALENDAR_ID']
MONGO_URL = ENV['MONGO_URL']
YOO_KASSA_TOKEN = ENV['YOO_KASSA_TOKEN']
ALEX_SPOON = ENV['ALEX_SPOON'].to_i
SPOON_TOKEN = ENV['SPOON_TOKEN'].to_i
MAIN_LOG_PATH = ENV['MAIN_LOG_PATH'].to_i
ERRORS_LOG_PATH = ENV['ERRORS_LOG_PATH'].to_i
OTHER_LOG_PATH = ENV['OTHER_LOG_PATH'].to_i
